### ISSUE TITLE
build_targets goes ot of bounds

### ISSUE THREAD

**Issue by micheleypf** [wangsssky/YOLO_Underwater#1]
Hi, I've been playing around with your code. Unfortunately the function **build_targets** which you use in each YOLOLayer sometimes goes out of bounds when building the **obj_mask**. It all starts from this line, apparently:

`Convert to position relative to box`
`
target_boxes = target[:, 2:6] * nG
`
If I understood your intention correcly, you are indexing each box but the indexing appears to be non-zero based. That's why at this line, at Tensor position 2 it might go out of bounds because gj = nG = obj_mask.shape[2]

`obj_mask[b, best_n, gj, gi] = 1`

**Comment by wangsssky** [comment]
Thank you very much for your report. I haven't met this before. I will look into it later, and it may take some time since I've been a little overload these days. Since I made up this project based on the popular YOLO repos, it is possible to see if is a solution there. Also maybe you could check your data to see if there are some irregular boxes that exist.

**Comment by micheleypf** [comment]
I am working on it, will let you know if I find anything

**Comment by micheleypf** [comment]
Hey I just got back at it today, indeed the problem occurs when bounding boxes are nearly touching the edge of the image. With a small offset the out of bounds I reported can be avoided.
Sorry I was misled by the value of **nG** and thought there might be a problem. Thanks
